apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: domain-name
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: domain.com
  dnsNames:
  - domain.com
  - www.domain.com    
  acme:
    config:
    - http01:
        ingressClass: nginx
    domains:
    - domain.com
    - www.domain.com
